{{- if not .Values.primary.persistence.dynamicVolumeProvisioning.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.primary.persistence.dynamicVolumeProvisioning.pvcName }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- if .Values.primary.persistence.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" .Values.primary.persistence.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.primary.persistence.labels }}
  labels: {{- include "common.tplvalues.render" (dict "value" .Values.primary.persistence.labels "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.primary.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size | quote }}
  {{- if .Values.primary.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.primary.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" .Values.primary.persistence "global" .Values.global) | nindent 2 }}
{{- end }}