apiVersion: v2
appVersion: 0.1.0

name: odoo

description: A Odoo Helm Chart
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
home: https://ptnglobalcorp.com/
sources:
- https://github.com/ptnglobalcorp/charts/tree/main/odoo

dependencies:
- name: common
  repository: oci://ghcr.io/nilnguyenkl/charts
  version: 0.1.0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://ghcr.io/nilnguyenkl/charts
  version: 0.1.0

version: 0.1.0