apiVersion: v2
appVersion: 0.1.0

name: odoo

description: A Odoo Helm Chart
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
home: https://ptnglobalcorp.com/
sources:
- https://github.com/ptnglobalcorp/charts/tree/main/odoo

dependencies:
- name: common
  repository: oci://registry-1.docker.io/ptnglobalcorp/common
  version: 0.1.0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/ptnglobalcorp/postgresql
  version: 0.1.0

annotations:
  artifacthub.io/maintainers: |
    - name: PTN Global
      email: support@ptnglobalcorp.com

version: 0.1.0