apiVersion: v2
version: 1.0.0
appVersion: 1.0.0

name: odoo
description: A Odoo Helm Chart For K8S
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png

dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: file://../postgresql
  # repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.4.7
- name: common
  repository: file://../common
  # repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.29.1