global:
  imageRegistry: ""

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
commonLabels: {}
commonAnnotations: {}

diagnosticMode:
  enabled: false

image:
  registry: docker.io
  repository: bitnami/odoo
  tag: 18.0.20250205-debian-12-r0
  digest: ""
  pullPolicy: IfNotPresent
  debug: false

odooEmail: user@example.com
odooSkipInstall: false
odooDatabaseFilter: .*
loadDemoData: false
allowEmptyPassword: false
replicaCount: 1
containerPorts:
  http: 8069

resourcesPreset: "large"
resources: {}

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 0

containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 0
  runAsGroup: 0
  runAsNonRoot: false
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
    add: ["CHOWN", "FOWNER", "SYS_CHROOT", "SETGID", "SETUID", "DAC_OVERRIDE"]
  seccompProfile:
    type: "RuntimeDefault"

livenessProbe:
  enabled: true
  initialDelaySeconds: 600
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  path: /web/health
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 12
  successThreshold: 1

automountServiceAccountToken: false
podLabels: {}
podAnnotations: {}
podAntiAffinityPreset: soft
affinity: {}
nodeSelector: {}
tolerations: []

updateStrategy:
  type: RollingUpdate
  rollingUpdate: null

service:
  type: ClusterIP
  ports:
    http: 80

  sessionAffinity: None
  clusterIP: ""
  annotations: {}

ingress:
  enabled: false
  ingressClassName: ""
  pathType: ImplementationSpecific
  apiVersion: ""
  hostname: odoo.local
  path: /
  annotations: {}
  tls: false
  selfSigned: false
  extraPaths: []

persistence:
  enabled: true
  volumeName: "data"
  resourcePolicy: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  accessMode: ReadWriteOnce
  size: 10Gi
  dataSource: {}
  annotations: {}
  selector: {}
  existingClaim: ""
  dynamicVolumeProvisioning:
    enabled: false
    pvName: ""
    pvcName: ""
    localPath: ""
    nodeAffinity:
      key: ""
      value: ""

serviceAccount:
  create: true
  name: ""
  automountServiceAccountToken: false
  annotations: {}

pdb:
  create: true
  minAvailable: ""
  maxUnavailable: ""

autoscaling:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: bn_odoo
    password: ""
    database: bitnami_odoo

networkPolicy:
  enabled: true