{{- if and (not .Values.persistence.dynamicVolumeProvisioning.enabled) .Values.persistence.dynamicVolumeProvisioning.pvName .Values.persistence.dynamicVolumeProvisioning.localPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.dynamicVolumeProvisioning.pvName }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - {{ .Values.persistence.accessMode | quote }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.persistence.dynamicVolumeProvisioning.localPath | quote }}
  claimRef:
    namespace: {{ .Release.Namespace | quote }}
    name: {{ .Values.persistence.dynamicVolumeProvisioning.pvName | quote }}
  nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: {{ .Values.persistence.dynamicVolumeProvisioning.nodeAffinity.key | default "kubernetes.io/hostname" }}
  #         operator: In
  #         values:
  #         - {{ .Values.persistence.dynamicVolumeProvisioning.value | default "ptn-k8s-worker-01" }}
{{- end }}