apiVersion: v2
appVersion: 0.1.0

description: A Library Helm Chart.
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
home: https://ptnglobalcorp.com/
sources:
  - https://github.com/ptnglobalcorp/charts/tree/main/odoo

version: 0.1.0
type: library