apiVersion: v2
appVersion: 0.1.0

name: common

description: A Library Helm Chart.
icon: https://bitnami.com/assets/stacks/odoo/img/odoo-stack-220x234.png
home: https://ptnglobalcorp.com/
sources:
  - https://github.com/ptnglobalcorp/charts/tree/main/common

annotations:
  artifacthub.io/maintainers: |
    - name: PTN Global
      email: support@ptnglobalcorp.com

version: 0.1.0
type: library